
name: Upload Kernel to Release5

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: 'URL kernel (GitHub / Mediafire / Mega)'
        required: true
        type: string
      kernel_mu:
        description: "Select the kernel source"
        required: false
        default: "s905x4"
        type: choice
        options:
          - s905x4
          - stable
          - dev
          - beta    
          - dtb  
          - tes
      rename_rootfs:
        description: "Rename rootfs"
        required: true
        default: ""
      target_repo:
        description: "Pilih repo tujuan upload (tes-rep, DIRGHA80, HOUJIE80)"
        required: false
        default: "tes-rep"
        type: choice
        options:
          - tes-rep
          - Dirgha80
          - Houjie80  

jobs:
  upload_kernel_release:
    runs-on: ubuntu-24.04

    steps:
      - name: Initialization environment (normal)
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip tar gzip qemu-utils mkisofs
          sudo apt-get -qq install jq python3 python3-pip
          pip install telethon
          pip install colorama
          sudo pip3 install gdown
          sudo pip3 install git+https://github.com/Juvenal-Yescas/mediafire-dl
          sudo mkdir -p /workdir/build
          sudo chown $USER:$GROUPS /workdir

      - name: Set Token and Target Repo
        id: choose_target
        run: |
          case "${{ github.event.inputs.target_repo }}" in
            tes-rep)
              echo "PAT=${{ secrets.TARGET_REPO_TES }}" >> $GITHUB_ENV
              echo "REPO_TARGET=tes-rep/kernel" >> $GITHUB_ENV ;;
            DIRGHA80)
              echo "PAT=${{ secrets.TARGET_REPO_DIRGHA80 }}" >> $GITHUB_ENV
              echo "REPO_TARGET=Dirgha80/kernel" >> $GITHUB_ENV ;;
            HOUJIE80)
              echo "PAT=${{ secrets.TARGET_REPO_HOUJIE80 }}" >> $GITHUB_ENV
              echo "REPO_TARGET=Houjie80/kernel2" >> $GITHUB_ENV ;;
            *)
              echo "::error ::Pilihan repo tidak valid!"; exit 1 ;;
          esac     

      - name: Download kernel
        run: |
          if echo "${{ github.event.inputs.kernel_url }}" | grep -q "drive."; then
            if echo "${{ github.event.inputs.kernel_url }}" | awk -F "/" '{print $6}' >/dev/null; then
              link_gdrive=$(echo "${{ github.event.inputs.kernel_url }}" | awk -F "/" '{print $6}')
            else
              link_gdrive=$(echo "${{ github.event.inputs.kernel_url }}" | awk -F "/" '{print $4}' | awk -F "?id=" '{print $2}' | awk -F "&export" '{print $1}')
            fi
            sudo gdown ${link_gdrive} -O /workdir/build/file.tar.gz
          elif echo "${{ github.event.inputs.kernel_url }}" | grep -q "mediafire.com"; then
            sudo mediafire-dl "${{ github.event.inputs.kernel_url }}" -o /workdir/build/file.tar.gz
          elif echo "${{ github.event.inputs.kernel_url }}" | grep -q "mega.nz"; then
            file_mega=$(sudo mega-get "${{ github.event.inputs.kernel_url }}" | awk -F: '{print $2}')
            sudo mv "${file_mega}" /workdir/build/file.zip
          else
            sudo wget --no-check-certificate "${{ github.event.inputs.kernel_url }}" -O /workdir/build/file.tar.gz
          fi
          ln -sf /workdir/build $GITHUB_WORKSPACE/build

      - name: Extract, Repack Nested Archives, Generate SHA256, and Final Bundle
        run: |
          mkdir -p /workdir/extracted
          mkdir -p /workdir/final
          sudo tar -xzf /workdir/build/file.tar.gz -C /workdir/extracted
          echo "‚úÖ File utama diekstrak"

          cd /workdir/extracted

          for archive in $(find . -type f -name "*.tar.gz"); do
            dirname=$(dirname "$archive")
            filename=$(basename "$archive" .tar.gz)
            folder="$dirname/$filename"
            mkdir -p "$folder"
            echo "üì¶ Mengekstrak: $archive -> $folder"
            sudo tar -xzf "$archive" -C "$folder"

            echo "üì¶ Mengarsip ulang: $filename.tar.gz"
            cd "$folder"
            sudo tar -czf /workdir/final/${filename}.tar.gz .
            cd - > /dev/null

        
          done

          echo "üì¶ Mengarsip semua hasil ke final-${{ inputs.rename_rootfs }}.tar.gz"
          cd /workdir/final
          sudo tar -czf /workdir/final/*.tar.gz -C /workdir/build/${{ inputs.rename_rootfs }}.tar.gz
          echo "‚úÖ Final archive berhasil dibuat: final-${{ inputs.rename_rootfs }}.tar.gz"

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: kernel_${{ inputs.kernel_mu }}
          file_glob: true
          overwrite: true
          body: |
            - The kernel can be used to compile Armbian and OpenWrt.
            - The kernel source code comes from: ${{ inputs.kernel_source }}
            - The kernel compilation toolchain: ${{ inputs.kernel_toolchain }}
            - The kernel version: ${{ inputs.kernel_version }}
            - The kernel nama: ${{ inputs.kernel_sign }}
            - This is a `${{ inputs.kernel_mu }}` kernel, which can be used in Armbian and OpenWrt.
            - ËøôÊòØ`Á®≥ÂÆöÁâà`ÂÜÖÊ†∏ÔºåÂèØ‰ª•Âú® Armbian Âíå OpenWrt Èáå‰ΩøÁî®„ÄÇ
            ## Supported Devices
            | Amlogic | MODEL | WIFI |
            | -------- | ------- | ------- |
            | **S905x**  | **HG680P**<br>**B860H** | **ON**<br>**NOT TEST** |
            | **S905X4** | **ADVAN AT01**<br>**AKARI** | **OFF**<br>**OFF** |
            | **S905x2** | **HG680FJ** | **NOT TEST** (`-`) |

      - name: Upload Kernel to Release (repo lain)
        uses: softprops/action-gh-release@v1
        if: ${{ env.PACKAGED_STATUS == 'success' || success() }} && !cancelled()
        env:
          GITHUB_TOKEN: ${{ env.PAT }}
        with:
          tag_name: kernel_${{ inputs.kernel_mu }}
          repository: ${{ env.REPO_TARGET }}  # GANTI dengan repo tujuan kamu
          name: Kernel_${{ inputs.kernel_mu }}
          body: |
            ### Kernel Build Information
            - Version: `${{ inputs.kernel_version }}`
            - Toolchain: `${{ inputs.kernel_toolchain }}`
            - Signature: `${{ inputs.kernel_sign }}`
            - Kernel Type: `${{ inputs.kernel_mu }}`
            ## Supported Devices
            | Amlogic | MODEL | WIFI |
            | -------- | ------- | ------- |
            | **S905x**  | **HG680P**<br>**B860H** | **ON**<br>**NOT TEST** |
            | **S905X4** | **ADVAN AT01**<br>**AKARI** | **OFF**<br>**OFF** |
            | **S905x2** | **HG680FJ** | **NOT TEST** (`-`) |

          files: build/*    
