name: Upload Kernel to Release

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: 'URL kernel (GitHub / Mediafire / Mega)'
        required: true
        type: string
      kernel_mu:
        description: "Select the kernel source"
        required: false
        default: "s905x4"
        type: choice
        options:
          - s905x4
          - stable
          - dev
          - beta    
          - dtb  
      rename_rootfs:
        description: "Rename rootfs"
        required: true
        default: ""

jobs:
  upload_kernel_release:
    runs-on: ubuntu-24.04

    steps:
      
      - name: Initialization environment (normal)
        # if: github.event.inputs.target != 'all' && !cancelled()
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip tar gzip qemu-utils mkisofs
          sudo apt-get -qq install jq python3 python3-pip
          pip install telethon
          pip install colorama
          sudo pip3 install gdown
          sudo pip3 install git+https://github.com/Juvenal-Yescas/mediafire-dl
          #wget https://mega.nz/linux/repo/xUbuntu_24.04/amd64/megacmd-xUbuntu_24.04_amd64.deb && sudo apt install "$PWD/megacmd-xUbuntu_24.04_amd64.deb"
          #sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir/build
          #sudo chown $USER:$GROUPS /workdir


      - name: Download kernel
        run: |
           if [ $(echo ${{ github.event.inputs.kernel_url }} | grep "drive.") ]; then
           if [ $(echo ${{ github.event.inputs.kernel_url }} | awk -F "/" '{print $6}') ]; then
            link_gdrive=$(echo ${{ github.event.inputs.kernel_url }} | awk -F "/" '{print $6}')
           else
            link_gdrive=$(echo ${{ github.event.inputs.kernel_url }} | awk -F "/" '{print $4}' | awk -F "?id=" '{print $2}'|awk -F "&export" '{print $1}')
           fi
           sudo gdown ${link_gdrive} -O /workdir/build/${{ inputs.rename_rootfs }}.tar.gz
           else
           if [ $(echo ${{ github.event.inputs.kernel_url }} | grep "mediafire.com") ]; then
            sudo mediafire-dl ${{ github.event.inputs.kernel_url }} -o /workdir/build/${{ inputs.rename_rootfs }}.tar.gz
            else
            if [ $(echo ${{ github.event.inputs.kernel_url }} | grep "mega.nz") ]; then
              file_mega=$(sudo mega-get ${{ github.event.inputs.kernel_url }} | awk -F: '{print $2}')
              sudo mv ${file_mega} build/file.zip
            else
              sudo wget --no-check-certificate ${{ github.event.inputs.kernel_url }} -O /workdir/build/${{ inputs.rename_rootfs }}.tar.gz
            fi
           fi
           fi    
           ln -sf /workdir/build $GITHUB_WORKSPACE/build
        

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: kernel_${{ inputs.kernel_mu }}
          file_glob: true
          overwrite: true
          body: |
            - The kernel can be used to compile Armbian and OpenWrt.
            - The kernel source code comes from: ${{ inputs.kernel_source }}
            - The kernel compilation toolchain: ${{ inputs.kernel_toolchain }}
            - The kernel version: ${{ inputs.kernel_version }}
            - The kernel nama: ${{ inputs.kernel_sign }}
            - This is a `${{ inputs.kernel_mu }}` kernel, which can be used in Armbian and OpenWrt.
            - 这是`稳定版`内核，可以在 Armbian 和 OpenWrt 里使用。
            ## Supported Devices
            | Amlogic | MODEL | WIFI |
            | -------- | ------- | ------- |
            | **S905x**  | **HG680P**<br>**B860H** | **ON**<br>**NOT TEST** |
            | **S905X4** | **ADVAN AT01**<br>**AKARI** | **OFF**<br>**OFF** |
            | **S905x2** | **HG680FJ** | **NOT TEST** (`-`) |

      - name: Upload Kernel to Release (repo lain)
        uses: softprops/action-gh-release@v1
        if: ${{ env.PACKAGED_STATUS == 'success' || success() }} && !cancelled()
        env:
          GITHUB_TOKEN: ${{ env.PAT }}
        with:
          tag_name: kernel_${{ inputs.kernel_mu }}
          repository: tes-rep/kernel  # GANTI dengan repo tujuan kamu
          name: Kernel_${{ inputs.kernel_mu }}
          body: |
            ### Kernel Build Information
            - Version: `${{ inputs.kernel_version }}`
            - Toolchain: `${{ inputs.kernel_toolchain }}`
            - Signature: `${{ inputs.kernel_sign }}`
            - Kernel Type: `${{ inputs.kernel_mu }}`
            ## Supported Devices
            | Amlogic | MODEL | WIFI |
            | -------- | ------- | ------- |
            | **S905x**  | **HG680P**<br>**B860H** | **ON**<br>**NOT TEST** |
            | **S905X4** | **ADVAN AT01**<br>**AKARI** | **OFF**<br>**OFF** |
            | **S905x2** | **HG680FJ** | **NOT TEST** (`-`) |

          files: build/*    
